apiVersion: agents.hermes-agent-operator.xyz/v1alpha1
kind: HermesAgent
metadata:
  labels:
    app.kubernetes.io/name: hermes-agent-operator
    app.kubernetes.io/managed-by: kustomize
  name: hermesagent-sample
spec:
  # TODO(user): Add fields here
